usuario = float(input("Ingrese un numero del 1 al 7: "))

if usuario > 7: print("El numero ingresado no es valido.")
elif usuario == 1: print("lunes")
elif usuario == 2: print("martes")
elif usuario == 3: print("miercoles")
elif usuario == 4: print("jueves")
elif usuario == 5: print("viernes")
elif usuario == 6: print("sábado")
else : print("domingo")
